version: "3"
services:
    tradingbot:
        image: tradingbot
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        volumes:
            - ./:/app
        command: bash -c "jupyter notebook --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.iopub_data_rate_limit=1.0e10"
